# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20160513_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='last_changing_products_update',
            field=models.DateTimeField(default=None, null=True, verbose_name='Time of last successful update which changed any product'),
        ),
        migrations.AddField(
            model_name='store',
            name='last_successful_update',
            field=models.DateTimeField(default=None, null=True, verbose_name='Time of last successful update'),
        ),
    ]
