version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    ports:
      - "5432:5432"
    restart: always
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      - POSTGRES_USER=spistresci

  mailhog:
    restart: always
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
