# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemodel',
            name='version_hash',
            field=models.CharField(default='', editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='xmldatafield',
            unique_together=set([('name', 'data_source')]),
        ),
    ]
