# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_auto_20160627_2239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xmldatafield',
            unique_together=set([('datafield_name', 'data_source')]),
        ),
    ]
