# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20160606_2315'),
        ('products', '0003_auto_20160601_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
