# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='last_update_revision',
            field=models.IntegerField(null=True),
        ),
    ]
