# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_chroniker_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='data_source_class',
            field=models.CharField(choices=[('Publio', 'Publio'), ('Woblink', 'Woblink'), ('XmlDataSource', 'XmlDataSource')], default='XmlDataSource', max_length=32),
        ),
        migrations.AddField(
            model_name='store',
            name='data_source_type',
            field=models.IntegerField(choices=[(1, 'Single XML')], default=1, verbose_name='Data source type'),
        ),
        migrations.AddField(
            model_name='store',
            name='data_source_url',
            field=models.URLField(default=None, verbose_name='URL address of data source'),
        ),
        migrations.AddField(
            model_name='store',
            name='enabled',
            field=models.BooleanField(default=True, help_text='If checked, Store will be updated according to schedule of defined jobs'),
        ),
    ]
