# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20160601_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(help_text='Url to main site of store'),
        ),
    ]
