# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20160603_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='last_changing_products_update',
        ),
        migrations.AddField(
            model_name='store',
            name='last_changing_offers_update',
            field=models.DateTimeField(default=None, null=True, verbose_name='Time of last successful update which changed any offer'),
        ),
    ]
