# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
        ('stores', '0005_auto_20160515_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='data_source_class',
        ),
        migrations.RemoveField(
            model_name='store',
            name='data_source_type',
        ),
        migrations.RemoveField(
            model_name='store',
            name='data_source_url',
        ),
        migrations.AddField(
            model_name='store',
            name='data_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datasource.DataSourceModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='last_update_revision',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
