# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0005_auto_20160627_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmldatafield',
            name='name',
        ),
    ]
