# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0006_remove_xmldatafield_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xmldatafield',
            unique_together=set([]),
        ),
    ]
